### PR TITLE
Fix External Downloaders / Logging / Local Page failure / Wait Interval

### PR DESCRIPTION
**Pull request by GlowingCrystallineEntity**
🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

## Proposed changes

There are really several changes in this commit, which are distinct but hard to separate at this point.  Apologies.

1) Fix Aria2 (and probably other external downloaders), that break with the "\\?\" that was added for Windows.  This took a bit of refactoring -- the call to normalize_path() converts a relative path to an absolute path, and we need the same sort of path no matter what downloader we use.  So I moved the call to this function up a level, so that I could make the path absolute no matter what, and then only "normalize" it if we were using the NativeDownloader.  It then has to be called from both the "old style" and "on demand" download methods.

The external downloaders still fail on long filenames, but at least they work most of the time (rather than not at all).  We need another solution for the long file names, or, we can do most of the downloading with the external one of choice, and then do a final run with the native(/internal) downloader, to get the missed files.

2)  The arguments that were being passed to Aria2 (1.24.0) were wrong.  Notably, it needed to have the target path and filename separated, which is why I still needed the absolute path as above.

3) The logging of skipped and failed URLs is enhanced to also write the results to a timestampped file, as well as stdout at the end of execution.  This allows the user to reference these files later, when they come back to the class.

3a) In order to track the failed URLs, the success/failure reporting had to be normalized up the call stack.  The lower level functions were returning just a "last update" for the downloaded file, or the external downloaders were just returning a process exit code; but the higher level ones were returning success/failure.  So I added the success/failure, and also refactored the failure container to always hold these URLs, and convey them up the stack.

3b) To both the URL success and failure logs, I added the file the program was trying to write, in addition to the URL it was trying to download.  This way, users can tell where the skipped/failed URL goes in the class syllabus, and/or manually download it if they wish.

4) The "local page" option was failing because it was writing (apparently) binary "UTF-8", but that wasn't specified in the open statements.  Simply adding "wb" or "rb" fixed the problem.

5) I changed the native downloader's "wait_interval" pause factor (base of the exponentiation) from 2 to 1.5.  There were complaints that the 63 second pause was annoyingly long, and I don't see its value.  This still gives a decent pause between retries, but doesn't wait so long.  If there's some reason for the longer pause, it can be changed back easily enough.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here
to help! This is simply a reminder of what we are going to look for before
merging your code._

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I agree to contribute my changes under the project's [LICENSE](/LICENSE)
- [ ] I have checked that the unit tests pass locally with my changes
- [ ] I have checked the style of the new code (lint/pep).
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

As mentioned in #533 , the tests don't pass locally, but the failures don't seem to be related to these changes.

I also don't have a local lint/pep at this point, but I've tried to conform to the project's style.  (and, btw, my IDE shows bunches of lint-like errors already in the code... ugh.) 

## Further comments

see above ;-)

### Reviewers
If you know the person who can review your code please add a @mention.

There are really several changes in this commit, which are distinct but
hard to separate at this point.  Apologies.

1) Fix Aria2 (and probably other external downloaders), that break with
the "\\?\" that was added for Windows.  This took a bit of refactoring
-- the call to normalize_path() converts a relative path to an absolute
path, and we need the same sort of path no matter what downloader we
use.  So I moved the call to this function up a level, so that I could
make the path absolute no matter what, and then only "normalize" it if
we were using the NativeDownloader.  It then has to be called from both
the "old style" and "on demand" download methods.

The external downloaders still fail on long filenames, but at least they
work most of the time (rather than not at all).  We need another
solution for the long file names, or, we can do most of the downloading
with the external one of choice, and then do a final run with the
native(/internal) downloader, to get the missed files.

2)  The arguments that were being passed to Aria2 (1.24.0) were wrong.
Notably, it needed to have the target path and filename separated, which
is why I still needed the absolute path as above.

3) The logging of skipped and failed URLs is enhanced to also write the
results to a timestampped file, as well as stdout at the end of
execution.  This allows the user to reference these files later, when
they come back to the class.

3a) In order to track the failed URLs, the success/failure reporting had
to be normalized up the call stack.  The lower level functions were
returning just a "last update" for the downloaded file, or the external
downloaders were just returning a process exit code; but the higher
level ones were returning success/failure.  So I added the
success/failure, and also refactored the failure container to always
hold these URLs, and convey them up the stack.

3b) To both the URL success and failure logs, I added the file the
program was trying to write, in addition to the URL it was trying to
download.  This way, users can tell where the skipped/failed URL goes in
the class syllabus, and/or manually download it if they wish.

4) The "local page" option was failing because it was writing
(apparently) binary "UTF-8", but that wasn't specified in the open
statements.  Simply adding "wb" or "rb" fixed the problem.

5) I changed the native downloader's "wait_interval" pause factor (base
of the exponentiation) from 2 to 1.5.  There were complaints that the 63
second pause was annoyingly long, and I don't see its value.  This still
gives a decent pause between retries, but doesn't wait so long.  If
there's some reason for the longer pause, it can be changed back easily
enough.

### CODE REVIEW

**Comment by GlowingCrystallineEntity** [comment]
Not sure how coverage decreased when I didn't add any functions/methods?  Or what to do about it?

**Comment by GlowingCrystallineEntity** [comment]
Ok, let me work on adding some test coverage... I added a lot of conditionals, and I suppose those aren't tested.

**Comment by GlowingCrystallineEntity** [comment]
Ok, let me work on adding some test coverage... I added a lot of conditionals, and I suppose those aren't tested.

I'm not so familiar with TDD/testing in Python, however -- are there any pointers that describe the mechanics, esp for this project, and on Windows?  thx.

**Comment by GlowingCrystallineEntity** [comment]
I don't see any tests for coursera-dl.py, and especially for download_on_demand_class().  Am I missing them?  I also don't see test coverage for the "if" clauses, implying the method isn't being tested.  So... of course adding lines of code is going to reduce the coverage % if there aren't any tests for the method...

Meanwhile, I'm guessing there are going to be conflicts now with #544 -- as that issue was also fixed in this check-in.

**Comment by balta2ar** [comment]
@GlowingCrystallineEntity https://github.com/coursera-dl/coursera-dl/blob/master/coursera/test/test_api.py

**Comment by GlowingCrystallineEntity** [comment]
Not to be dense, but which of those fixtures tests the download methods in coursera-dl.py, such as download_on_demand_class() ?

**Comment by balta2ar** [comment]
Not download methods, parsing methods. `parse_on_demand_syllabus` is basically tested in `test_api.py`.

**Comment by GlowingCrystallineEntity** [comment]
Yes, that's what it looks like to me, too.  But most of the new lines I added were in that download method, and that's what reduced the coverage % that made the coverage test fail.  So there's not really anything I can do about that....

**Comment by GlowingCrystallineEntity** [comment]
Plus, these conflicts now need to be resolved.  I was thinking that it would be easier to get this PR committed, and then move the functionality into the "old style" download method.  But it's too late for that now...

**Comment by GlowingCrystallineEntity** [comment]
Actually, as of yesterday, do we have any "old style" courses left?

**Comment by balta2ar** [comment]
> So there's not really anything I can do about that....

You can add new tests. In fact, I suggest that you do that. We should put in stone this behavior when UNC is not added for external downloader.

**Comment by GlowingCrystallineEntity** [comment]
I'd add new tests for my own code, but for me, right now, adding tests that are missing altogether is a larger project than I can commit to I'm afraid....

**Comment by GlowingCrystallineEntity** [comment]
Wondering if this PR is going to be accepted as-is?  If not, I'll cancel it....

**Comment by balta2ar** [comment]
I've been waiting for tests, you said you'd add them.

Meanwhile, I'd doing some refactoring. You're definitely gonna have lots of conflicts after that. We have two options here:

1. You add tests to the old code. I finish refactoring and you rebase your work on top of new master.
2. You add tests to the old code. I finish refactoring and draw ideas from your pull request, and apply some of them by my own.

I suggest that you add tests anyway, that's really helpful.

**Comment by GlowingCrystallineEntity** [comment]
Read what I wrote two posts above yours.  And I already merged one set of conflicting changes.

Apparently, pull requests can't be deleted on GitHub, otherwise I would do so at this point.

**Pull request closed without merging**
