### PR TITLE
Saved README.md with Dillinger.io

### PR DESCRIPTION
**Pull request by code-is-god**
Updated documentation about using the `--on-demand` option while downloading courses starting with URL `https://www.coursera.org/learn/`

### CODE REVIEW

**Comment by code-is-god** [comment]
Reverted the unwanted changes. Thanks.

**Comment by balta2ar** [comment]
For the future: please write meaningful commit messages. I have no idea what dillinger.io has to do with coursera-dl.

**Comment by balta2ar** [comment]
Why add other paragraph about on demand course? What you've added is almost exact duplicate of the line before: `To download an On Demand course, use the --on-demand option of the
program.`. It would be more logical to me to extend the existing description, e.g. `To download an On Demand course (its URL stats with https://www.coursera.org/learn/), use...`

**Comment by code-is-god** [comment]
Thanks for the feedback. Its my first commit on github, so learning the ropes. 

It looks like not all on demand courses start with `https://www.coursera.org/learn/`. Historically, the coursera courses used to begin with `https://class.coursera.org/<CLASS_NAME>/class/index`

Recently, coursera has changed the layout for (some?) on demand courses resulting in the link changing to `https://www.coursera.org/learn/`.

There were some issues raised regarding this [#387], [#400] which is where I thought on updating the docs.

**Comment by balta2ar** [comment]
> It looks like not all on demand courses start with https://www.coursera.org/learn/. Historically, the coursera courses used to begin with https://class.coursera.org/<CLASS_NAME>/class/index

Are you sure? I've never seen such a course. In the issues you've referenced it's was either missing `--on-demand` or extra `-sf` option. Please provide URL of such course if I'm wrong.

**Comment by code-is-god** [comment]
ok, maybe i am not. I tried looking for on-demand courses not starting with `https://www.coursera.org/learn/` and failed.

However found [this](https://learner.coursera.help/hc/en-us/articles/203879739-Course-Types) help article saying "courses on the new platform have URLs that begin with `www.coursera.org/learn`", indicating non on-demand courses might also start with `www.coursera.org/learn`. Not relevant to this commit, but just a call-out.

Regarding this commit, maybe we revert back and close it?

**Pull request closed without merging**
