### PR TITLE
Docker image for coursera-dl

### PR DESCRIPTION
**Pull request by opsxcq**
## Proposed changes

Create a dockerfile and published at (`strm/coursera-dl`).

## Types of changes

- [X] New feature (non-breaking change which adds functionality)

## Checklist

- [X] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [X] I agree to contribute my changes under the project's [LICENSE](/LICENSE)
- [X] I have checked that the unit tests pass locally with my changes
- [X] I have checked the style of the new code (lint/pep).
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

## Further comments

Tests weren't added, but the build status can be checked [here](https://hub.docker.com/r/strm/coursera-dl/builds/).

### CODE REVIEW

**Comment by rbrito** [comment]
Dear @opsxcq,

First of all, thank you very much for your pull request.

We already have some Docker support at https://github.com/coursera-dl/coursera-dl/tree/master/deploy

Can you make suggestions/modifications to that? I only know the basics of Docker and I would appreciate it if someone took maintainership of what we already have. Would you want to be the maintainer of that part of the project?

Thanks,

Rogério Brito.

**Comment by opsxcq** [comment]
Sure, I can be the maintainer of this docker image, as well the maintainer of the `edx-dl` image if possible.

About the current docker support:

- `FROM ubuntu:14.04` - Is a very old image, better use a `python` image directly (Already in this PR)
- [Multiple run commands that will create several unnecessary layers](https://github.com/coursera-dl/coursera-dl/blob/0ec980514d3d77c24486f198f631c4be7228f680/deploy/Dockerfile#L4-L7)
- [In this line](https://github.com/coursera-dl/coursera-dl/blob/0ec980514d3d77c24486f198f631c4be7228f680/deploy/Dockerfile#L12) you don't need to clone this repo, since we are in a git repo you can just add the local copy, it help if someone want to build their copy locally to test a feature, run the unit tests, or in the CI (Docker hub for example) to build the image.
- [Those lines](https://github.com/coursera-dl/coursera-dl/blob/0ec980514d3d77c24486f198f631c4be7228f680/deploy/Dockerfile#L9-L10) - is better to avoid adding anything like that, containers must be ephemeral, any information regarding authentication or keys, better to be mapped to parameters (They already are), or in the case of a keyfile, is better to keep them in a binding (`-v`).
- [This line](https://github.com/coursera-dl/coursera-dl/blob/0ec980514d3d77c24486f198f631c4be7228f680/deploy/Dockerfile#L13) is better to install the dependencies before you add the code to the repository, it optimizes the layers created by docker, so at any update, users will only have to download a layers with the size of your code, if you install the dependencies after that, you will force the users to download your code + the whole dependencies always that this repo is updated.
- The image doesn't set an entrypoint, for docker, this is the default binary that will be run when the container is started.

Another good practice is to add this image do docker hub, so any `docker pull image-name` will be enough to any docker user who wants to run this code. I already took care of this, any merge from this repo to mine, will trigger the build, if you prefer is possible to create an official group for coursera-dl where you have access, but it will require someone with access to this repository to configure the integration with docker hub. I can assist you if needed to configure this integration.

**Comment by rbrito** [comment]
@opsxcq, First of all, sorry for the late reply.

Second, your explanations were very illuminating, since I know only the bare essentials of Docker.

Third, can you send a new commit to this pull request so that we remove the previous docker file, with an appropriate documentation? Preferably, your previous email as the commit message would be best.

Oh, and I will promptly merge it and we can make your image official at last!

Thanks,

Rogério.

**Comment by opsxcq** [comment]
Thank you @rbrito ! I've applied the requested changes.

**Pull request merged**
