### PR TITLE
Added pip3 installation comments to README.md

### PR DESCRIPTION
**Pull request by Make42**
Added line 97 to 103

### CODE REVIEW

**Comment by rbrito** [comment]
Please, can you resend your contribution from your `Make42/Make42-patch-1` branch, instead of from your `master` branch? This way, we don't have the spurious merge commit.

If you don't know how to do that, please let me know and I will try to assist. :)

**Comment by Make42** [comment]
I am not sure how to do that. I know about branches, merging etc. but I have done everything on command line so far (I am a novice).

**Comment by rbrito** [comment]
@Make42, do you want things the quick way or the right way? :) Both will end up with the same result, but one is conceptually "cleaner".

Anyway, the quicker way is the following:

* check that you are in you master branch with `git status`
* check that your last commit is, indeed, your merge commit with `git show`
* if it is, then use `git reset HEAD^`, which will "undo" your merge commit (don't worry; you can still "undo" this "undo"). :)
* see if you still have your comment with `git show -p`

Of course, I can merge it very quickly, but I suppose that your intention here is to learn, right? :)

**Comment by Make42** [comment]
So what is the right way? :-)

**Comment by rbrito** [comment]
@Make42, it's not really a "better" way (more comments on that later), but the following will do:

```
git clone https://github.com/Make42/coursera-dl
cd coursera-dl
git reset HEAD^
git checkout -- .
git cherry-pick d13ccab
git push --force
```

This pull request will be (should be) updated automatically.

Actually, now that I think about it, it is probably a worse solution, but it will, at least, keep our history clean. :)

Later, we can continue with a better strategy, but let's get your contributions merged already! :)

Oh, and, please, *do* keep on contributing (even if it is just the documentation---we really need better documentation).

If you feel like it, just go ahead and start a wiki page on our project, for documentation purposes: https://github.com/coursera-dl/coursera-dl/wiki


Thanks,

Rogério.

**Comment by rbrito** [comment]
@Make42, I just went ahead and decided to cherry-pick manually your important commit, so that we speed up things.

Please, now that you made your first contribution, please, don't stop and continue tweaking the code and/or documentation!

Thanks a lot!

**Pull request closed without merging**
