### PR TITLE
Add extraction of supplementary materials in on-demand courses

### PR DESCRIPTION
**Pull request by balta2ar**
Supplementary materials are usually located on the first page of a
module. These materials include: pdf, zip, ipynb, csv and other files.
The code uses undocumented but "reverse engineered" (in browser) method:
https://www.coursera.org/api/onDemandSupplements.v1. The code handles
cases when there are multiple files of different formats (extensions)
on the same page and downloads them all. This clearly benefits to the users
which will now automatically get all the necessary files for practical
assignments.

One remarkable downside of this change is that new lecture is now added
to the beginning of the list of lectures. It means that lectures will
be renumbered, which will cause downloads of old lectures (even if they
are already downloaded). I suggest removing ongoing on-demand courses
and downloading them again (Internet connection permitting). Alternatively,
one can use hardlink utility to find duplicate files and turn them into
hardlinks to save up disk space.

Another minor flaw is that occasionally supplementary HTML pages are
downloaded and saved to filenames without extensions, e.g.

> 01_reading-recommending-songs-assignment_graphlab.SFrame.groupby.html#graphlab.SFrame.groupby

Technically, extension here is "groupby" but that looks ugly. I consider
this to be a very minor issue. Anyway, suggestions are welcome.

### CODE REVIEW

**Comment by balta2ar** [comment]
@rbrito @mxamin @iemejia Guys, please take a look.

There is one test failing on Travis-CI. All tests pass locally. I think it might be related to either new Travis-CI infrastracture or newer version of python-keyring. I have created an issue in the latter one with a question: https://github.com/jaraco/keyring/issues/203

**Comment by balta2ar** [comment]
Looks like there is room for improvement. Certain courses put supplementary materials inside assignment page. Looks like it's not scanned. For example: https://www.coursera.org/learn/vvedenie-mashinnoe-obuchenie/programming/UzPbw/sostavlieniie-fondovogho-indieksa

**Comment by balta2ar** [comment]
Programming assignments have special type `gradedProgramming`:
``` js
              {
                "id": "UzPbw",
                "slug": "sostavlieniie-fondovogho-indieksa",
                "name": "Составление фондового индекса",
                "timeCommitment": 10800000,
                "content": {
                  "typeName": "gradedProgramming",
                  "definition": {
                    "programmingAssignmentId": "zWvUX6jeEeWV-A6Oxpvjnw@15",
                    "gradingWeight": 5
                  }
                }
              }
```

CourseID + ItemID gives us the following link https://www.coursera.org/api/onDemandProgrammingLearnerAssignments.v1/01XLylXyEeWKXg4Y7_tPaw~UzPbw?fields=maxScore%2CpassingFraction%2CpassingScore%2CsubmissionLearnerSchema%2CsubmissionBuilderSchema%2CversionId with metadata about the assignment:
``` js

elements: [{id: "01XLylXyEeWKXg4Y7_tPaw~UzPbw", courseId: "01XLylXyEeWKXg4Y7_tPaw", itemId: "UzPbw",…}]
0: {id: "01XLylXyEeWKXg4Y7_tPaw~UzPbw", courseId: "01XLylXyEeWKXg4Y7_tPaw", itemId: "UzPbw",…}
courseId: "01XLylXyEeWKXg4Y7_tPaw"
id: "01XLylXyEeWKXg4Y7_tPaw~UzPbw"
itemId: "UzPbw"
maxScore: 3
passingFraction: 0.8
passingScore: 3
submissionBuilderSchema: {typeName: "files", definition: {,…}}
definition: {,…}
typeName: "files"
submissionLearnerSchema: {typeName: "multipart",…}
definition: {assignmentInstructions: {typeName: "cml", definition: {dtdId: "assess/1",…}},…}
assignmentInstructions: {typeName: "cml", definition: {dtdId: "assess/1",…}}
definition: {dtdId: "assess/1",…}
dtdId: "assess/1"
value: "<co-content><text/><asset id="yeJ7Q8VAEeWPRQ4YsSEORQ" name="statement-pca" extension="pdf" assetType="generic"/><text>Данное задание основано на материалах лекций по методу главных компонент и посвящено знакомству с методом.</text><heading level="2">Вы научитесь: </heading><list bulletType="bullets"><li><text>работать с методом главных компонент</text></li><li><text>использовать его для вычисления улучшенного индекса Доу-Джонса</text></li></list><heading level="2">Введение</heading><text>Метод главных компонент (principal component analysis, PCA) — это один из методов обучения без учителя, который позволяет сформировать новые признаки, являющиеся линейными комбинациями старых. При этом новые признаки строятся так, чтобы сохранить как можно больше дисперсии в данных. Иными словами, метод главных компонент понижает размерность данных оптимальным с точки зрения сохранения дисперсии способом.</text><text>Основным параметром метода главных компонент является количество новых признаков. Как и в большинстве методов машинного обучения, нет четких рекомендаций по поводу выбора значения этого параметров. Один из подходов — выбирать минимальное число компонент, при котором объясняется не менее определенной доли дисперсии (это означает, что в выборке сохраняется данная доля от исходной дисперсии).</text><text>В этом задании понадобится измерять схожесть двух наборов величин. Если имеется набор пар измерений (например, одна пара — предсказания двух классификаторов для одного и того же объекта), то охарактеризовать их зависимость друг от друга можно с помощью корреляции Пирсона. Она принимает значения от -1 до 1 и показывает, насколько данные величины линейно зависимы. Если корреляция равна -1 или 1, то величины линейно выражаются друг через друга. Если она равна нулю, то линейная зависимость между величинами отсутствует.</text><heading level="2">Данные</heading><text>В этом задании мы будем работать с данными о стоимостях акций 30 крупнейших компаний США. На основе этих данных можно оценить состояние экономики, например, с помощью индекса Доу-Джонса. Со временем состав компаний, по которым строится индекс меняется. Для набора данных был взят период с 23.09.2013 по 18.03.2015, в котором набор компаний был фиксирован (подробнее почитать о составе можно по ссылке из материалов). </text><text>Одним из существенных недостатков индекса Доу-Джонса является способ его вычисления — при подсчёте индекса цены входящих в него акций складываются, а потом делятся на поправочный коэффициент. В результате, даже если одна компания заметно меньше по капитализации, чем другая, но стоимость одной её акции выше, то она сильнее влияет на индекс. Даже большое процентное изменение цены относительно дешёвой акции может быть нивелировано незначительным в процентном отношении изменением цены более дорогой акции.</text><heading level="2">Реализация в sklearn</heading><text>Метод главных компонент реализован в пакете scikit-learn в модуле decomposition в классе <a href="http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html\">PCA</a>. Основным параметром является количество компонент (n_components). Для обученного преобразования этот класс позволяет вычислять различные характеристики. Например, поле <em>explained_variance_ratio_</em> содержит процент дисперсии, который объясняет каждая компонента. Поле <em>components_ </em>содержит информацию о том, какой вклад вносят признаки в компоненты. Чтобы применить обученное преобразование к данным, можно воспользоваться методом <a href="http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html#sklearn.decomposition.PCA.transform">transform</a>. </text><text>Для нахождения коэффициента корреляции Пирсона можно воспользоваться функцией <a href="http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.corrcoef.html">corrcoef</a> из пакета numpy.</text><heading level="2">Материалы</heading><list bulletType="bullets"><li><text><a href="https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average">Dow Jones Industrial Average</a></text></li><li><text><a href="https://en.wikipedia.org/wiki/Historical_components_of_the_Dow_Jones_Industrial_Average">История состава компаний, входящих в индекс Dow Jones</a></text></li></list><heading level="2">Инструкция по выполнению</heading><list bulletType="numbers"><li><text>Загрузите данные close_prices.csv. В этом файле приведены цены акций 30 компаний на закрытии торгов за каждый день периода. </text></li><li><text>На загруженных данных обучите преобразование PCA с числом компоненты равным 10. Скольких компонент хватит, чтобы объяснить 90% дисперсии?</text></li><li><text>Примените построенное преобразование к исходным данным и возьмите значения первой компоненты. </text></li><li><text> Загрузите информацию об индексе Доу-Джонса из файла djia_prices.csv. Чему равна корреляция Пирсона между первой компонентой и индексом Доу-Джонса? </text></li><li><text>Какая компания имеет наибольший вес в первой компоненте?</text></li></list><text>Если ответом является нецелое число, то целую и дробную часть необходимо разграничивать точкой, например, 0.42. При необходимости округляйте дробную часть до двух знаков.</text><text>Ответ на каждое задание — текстовый файл, содержащий ответ в первой строчке. Обратите внимание, что отправляемые файлы не должны содержать пустую строку в конце. Данный нюанс является ограничением платформы Coursera. Мы работаем над тем, чтобы убрать это ограничение.</text><asset id="jrUPcLvFEeW6FApX76Rguw" name="djia_index" extension="csv" assetType="generic"/><asset id="jqxc37vFEeW6FApX76Rguw" name="close_prices" extension="csv" assetType="generic"/><text/><text/><text/><text/><text/></co-content>"
typeName: "cml"
```

That's only part of the output. In this output we need to find all `<value>` tags. They contain `<asset>` tags:
``` xml
  <asset id="yeJ7Q8VAEeWPRQ4YsSEORQ" name="statement-pca"
  extension="pdf" assetType="generic" />
  <asset id="jrUPcLvFEeW6FApX76Rguw" name="djia_index"
  extension="csv" assetType="generic" />
  <asset id="jqxc37vFEeW6FApX76Rguw" name="close_prices"
  extension="csv" assetType="generic" />
```

Now I wonder how to turn `asset` tag into a direct link, e.g.: https://d3c33hcgiwev3.cloudfront.net/_3cdeda0745801a9686d7f5601010fb0c_statement-pca.pdf?Expires=1454198400&Signature=h5uo5XCq8DN-X6jf9VpJXj5-0M3LfBQmgf6LamlkrmH9YexVGjbVc3McRfvivJ9eQDXPo~ZujKw7YLc8BnCjDZA5hfwpF5q2J7dk4-ssK2ZA2-AIAukuURURZqFypiR7qbEFUHtDnWlSP16Q59X8D1g-PtVIEMUop4fgvGs3Px4_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A

**Comment by balta2ar** [comment]
Okay, looks like the puzzle is solved. These is an API method: https://www.coursera.org/api/assetUrls.v1?ids=yeJ7Q8VAEeWPRQ4YsSEORQ%2CjrUPcLvFEeW6FApX76Rguw%2Cjqxc37vFEeW6FApX76Rguw which returns:
``` json
{
  "elements": [
    {
      "id": "jqxc37vFEeW6FApX76Rguw",
      "url": "https://d3c33hcgiwev3.cloudfront.net/_82b4a9f66c689b3d40dd25ebd761b07f_close_prices.csv?Expires=1454198400&Signature=bfgnJPMO7gugESqp6LRRdO-HP0X8~Y19GK9BGPjdU4bJQlR79iDLNgNMlAaCb3GhzyBAqv~46zr1XPY8VLY-QY2E0mnPVXlNLzgnS6Ypf2i~2J4jpI5UpGS4tuyT3mKxweaMttgTl3YvQFqSZX9an-TZRCDjgu57ucKfSAHkwRc_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A",
      "expires": 1454198400000
    },
    {
      "id": "yeJ7Q8VAEeWPRQ4YsSEORQ",
      "url": "https://d3c33hcgiwev3.cloudfront.net/_3cdeda0745801a9686d7f5601010fb0c_statement-pca.pdf?Expires=1454198400&Signature=h5uo5XCq8DN-X6jf9VpJXj5-0M3LfBQmgf6LamlkrmH9YexVGjbVc3McRfvivJ9eQDXPo~ZujKw7YLc8BnCjDZA5hfwpF5q2J7dk4-ssK2ZA2-AIAukuURURZqFypiR7qbEFUHtDnWlSP16Q59X8D1g-PtVIEMUop4fgvGs3Px4_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A",
      "expires": 1454198400000
    },
    {
      "id": "jrUPcLvFEeW6FApX76Rguw",
      "url": "https://d3c33hcgiwev3.cloudfront.net/_82b4a9f66c689b3d40dd25ebd761b07f_djia_index.csv?Expires=1454198400&Signature=ev67ad4IofngeNCBOxHN1bQ3DVQ48puKT7cW0-yHR7FlcypM9~12mnBKOkmD8yaiZlXCR8Mf5CY1KckPSHZKnxOqtgRacy7Ez5qvG1w50QIH0~NDMMZMD2uXgcnssv1ISiuMAST51~Qdlu5HwY8TL6zYTn56QEQbT9xe80V4TVc_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A",
      "expires": 1454198400000
    }
  ],
  "paging": null,
  "linked": null
}
```

So to summarize the steps required to download supplements from assignments, we need to:

1. Take `gradedProgramming` item, remember its `id`.
2. Use this method to collect assignments instructions: https://www.coursera.org/api/onDemandProgrammingLearnerAssignments.v1/01XLylXyEeWKXg4Y7_tPaw~UzPbw?fields=submissionLearnerSchema
3. Collect all `elements[*].submissionLearnerSchema.definition.assignmentInstructions.definition.value` and extract all `asset` tags. Attributes `id`, `name`, `extension` are useful.
4. Obtain direct links by calling https://www.coursera.org/api/assetUrls.v1?ids=yeJ7Q8VAEeWPRQ4YsSEORQ, grab all `elements[*].url`.
5. [optional] If you use direct `url` from `assertUrls` request, filename is ugly, it contains some hash `_3cdeda0745801a9686d7f5601010fb0c_statement-pca.pdf`. A better way to prettify it is to match its `id` with ids collected in step 3, and use `name` and `extension` attributes from there.

By the way, this pull request is supposed to fix #425.

**Comment by balta2ar** [comment]
I've added code to extract files form programming assignment pages. I moved a couple of methods that perform extraction into a separate class `CourseraOnDemand`. Unfortunately, not all the methods that work with new Coursera layout were moved, so extractions methods are spread out across two modules. This can be easily fixed next time we need updating those methods.

**Comment by rbrito** [comment]
@balta2ar, To be honest, this whole thread of yours with all the trial and errors is so informative that I would love to see it somehow in our history or whatever.

Whenever I clone a new project or I try to remember how my own projects work after some time, I use gitk to browse locally the commits and the informative commit messages are *the* most helpful item in understanding the code.

Furthermore, your documentation markup of the docstrings is great and I think that we could publish it in our (soon to be present) website.

@victorwestmann, you sent me privately a tarball/zip/whatever of a proposal of the website. Can you create a fork of this repository of ours and send pull requests of what you had?

Once we have that, integrating the documentation automatically generated from our code would rock greatly (e.g., something like the documentation of the `requests` library or similar ones).

Thanks to you all.

**Comment by victorwestmann** [comment]
I sure can @rbrito. It would be a pleasure to help. Just, please, if possible, create a website of the project. Then I'll submit the files. :smile:

**Pull request merged**
