### PR TITLE
Extract more programming assignments

### PR DESCRIPTION
**Pull request by balta2ar**
This pull request implements:

1. Handle another case when programming assignment files are not extracted (see data-structures, algorithms-on-graphs courses as an example)
2. Support text extraction from supplementary and programming assignment sections:
   * text is converted to a more HTML-friendly version
   * images are locally embedded into the HTML page (e.g. in parprog1 course)
   * MathJax URI script tag is injected so that math can be rendered when page is opened locally (e.g. in linear-regression-model course)
3. Add more debug output when running with --debug option.

Related: #490

### CODE REVIEW

**Comment by balta2ar** [comment]
@rbrito @iemejia @shk3 Guys, please review.

Few things concern me about this pull request:

* Decomposition is not ideal. I'm starting to feel that we need to break `CourseraOnDemand` class into smaller parts.
* `IN_MEMORY_MARKER` looks ugly. Please share your thoughts on how to make it better.

I'm open to suggestions, please feel free to comment and discuss better implementation.

What is left to do:
- [ ] Convert LaTeX to images in instructions text.
- [ ] Research how quizzes are retrieved/stored/displayed.

**Comment by mrageh** [comment]
@balta2ar Thanks for doing this PR. It looks like a good first draft and I'd like to use this functionality to download a few old courses from Coursera before they're removed, any chance you can finish this before June 30th.

**Comment by balta2ar** [comment]
@mrageh To be honest, I did not plan to support old-style courses. This patch is only about OnDemand courses.

Could you go over your old courses and save everything you need in assignments manually? I'm afraid that's the only realistic scenario considering the situation with this upcoming Coursera shut-down.

**Comment by balta2ar** [comment]
@rbrito @iemejia Coursera old courses shut-down and recent post on HackerNews had brought us some new stars and hopefully new users, so I merged this pull request sooner. Hopefully, more people can start using new functionality. Feel free to review and comment on the implementation anyway.

Also I think I screwed things a little bit during the rebase/merge as I can see duplicate commits in the history now. Sorry, I'm git novice.

**Pull request merged**
