### PR TITLE
Switch to API subdomain for API URL defines.

### PR DESCRIPTION
**Pull request by TheGoddessInari**
Started hitting errors today, switch from www.coursera.org/api/ to api.coursera.org/api/ to fix.

🚨Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

## Proposed changes

coursera-dl no longer appears to be working grabbing urls from the www subdonain as of this afternoon (was working some hours ago), the api subdomain works in my testing.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here
to help! This is simply a reminder of what we are going to look for before
merging your code._

- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I agree to contribute my changes under the project's [LICENSE](/LICENSE)
- [x] I have checked that the unit tests pass locally with my changes
- [ ] I have checked the style of the new code (lint/pep).
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, please explain why you chose
the solution you did and what alternatives you considered, etc.

### Reviewers
If you know the person who can review your code please add a @mention.

### CODE REVIEW

**Comment by balta2ar** [comment]
@TheGoddessInari How did you found out that? I see no `api.` subdomain prefix in requests in my browser console, but the script is indeed broken for me and adding prefixes works.

**Comment by Moulick** [comment]
yeah @TheGoddessInari, how the heck did you figure this out ?

**Comment by Moulick** [comment]
Also, the Subtitles are failing to download.

The following URLs (112) could not be downloaded:
--------------------------------------------------------------------------------
https://www.coursera.org/api/subtitleAssetProxy.v1/XxCKGAdzSNaQihgHc9jWmg?expiry=1528070400000&hmac=O7H6Rk4rioEoeSfpaAcDyYVOwq7ALbDKAG7G8XmIXTw&fileExtension=srt
https://www.coursera.org/api/subtitleAssetProxy.v1/XxCKGAdzSNaQihgHc9jWmg?expiry=1528070400000&hmac=nCSxQ_Q4_nQHjFhlm0WcOnLBVOQVJ-rUbVizlLkLnCc&fileExtension=txt
https://www.coursera.org/api/subtitleAssetProxy.v1/c8nqAPQASn2J6gD0ACp9Zw?expiry=1528070400000&hmac=b02GpBCLLfFsOZd-ieI8mYlvaJOmLxJ0ASB4q8QYV1s&fileExtension=srt

**Comment by TheGoddessInari** [comment]
Honestly? I just saw it break and guessed that they changed stuff (at least as far as coursera-dl is concerned) without actually posting about it or telling anyone. Saw that the api subdomain had the same info, tested and validated it.

The subtitles are the same issue, technically.
```
coursera/api.py
19:from .utils import (BeautifulSoup, make_coursera_absolute_url,
925:                    ] = make_coursera_absolute_url(subtitle_url)

coursera/utils.py
238:def make_coursera_absolute_url(url):
```
make_coursera_absolute_url puts www.coursera.org on front, and it's only used for the subtitles right now.

**Comment by Moulick** [comment]
@TheGoddessInari hmm, that rather perceptive of you, awesome. The thing about the subs is that, they are downloading fine with `--aria2`. what gives ?

**Comment by balta2ar** [comment]
Upgrading from TLSv1.0 to TLSv1.2 helped even with the older urls, but I'd leave the changes as it makes sense to use urls that start with an api, plus I see no harm leaving it as is.

**Comment by dhanu10896** [comment]
@TheGoddessInari  thanks, man!
And how do you got to know that they have changed urls?

**Comment by TheGoddessInari** [comment]
As a post-mortem, making an educated guess, it ended up having to do with Cloudflare (which covers www.coursera.org) and [this change](https://support.cloudflare.com/hc/en-us/articles/360003205452-Using-Minimum-TLS-Version-in-Cloudflare-Crypto). It almost certainly has to do with the part about PCI compliance demanding a changeover to TLS 1.2 minimum on June 1st.

**Pull request merged**
